# Generated by Django 2.2.7 on 2020-01-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irisapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='petal_length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='feature',
            name='petal_width',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='feature',
            name='sepal_length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='feature',
            name='sepal_width',
            field=models.FloatField(),
        ),
    ]
